### ISSUE TITLE
Questions about the pSp encoder with Z+

### ISSUE THREAD

**Issue by kasim0226** [williamyang1991/DualStyleGAN#10]
1. Could you share how you modified pSp encoder with Z+?
I could not find the details in the paper and codes.
It seems you didn't use VAE encoder of the AgileGAN and also didn't inference Z mean and Z standard. 
The modification of pSp encoder is only passing output (Z+) of pSp encdoer to mapping layer indviually? Am I right?
2. How did you train the pSp encoder with Z+? Or you used the pretrained pSp encoder model directly?
Looking forward to your reply.

**Comment by williamyang1991** [comment]
> 1. Could you share how you modified pSp encoder with Z+?
>    I could not find the details in the paper and codes.
>    It seems you didn't use VAE encoder of the AgileGAN and also didn't inference Z mean and Z standard.
>    The modification of pSp encoder is only passing output (Z+) of pSp encdoer to mapping layer indviually? Am I right?

Yes, the encoder just maps the input image to Z+ output without using VAE.

> 2. How did you train the pSp encoder with Z+? Or you used the pretrained pSp encoder model directly?

**(I)** I modify the stylegan model (pSp decoder) so that it accepts Z+ input: https://github.com/williamyang1991/DualStyleGAN/blob/39a9e9e8d6ea51a817ab50fbcf82d336275abf15/model/stylegan/model.py#L511-L523

**(2)** I modify pSp encoder so that it passes the options `z_plus_latent` and `return_z_plus_latent` to the pSp decoder
https://github.com/williamyang1991/DualStyleGAN/blob/39a9e9e8d6ea51a817ab50fbcf82d336275abf15/model/encoder/psp.py#L69-L70
https://github.com/williamyang1991/DualStyleGAN/blob/39a9e9e8d6ea51a817ab50fbcf82d336275abf15/model/encoder/psp.py#L97-L101
and return Z+
https://github.com/williamyang1991/DualStyleGAN/blob/39a9e9e8d6ea51a817ab50fbcf82d336275abf15/model/encoder/psp.py#L106-L108

**(3)** I modify the function `train()` and `validate()` of `coach.py` in the official pSp code, so that it passes our training option `opts.z_plus_latent` to the pSp model.

* changing  Line 91 to `y_hat, latent = self.net.forward(x, return_latents=True, z_plus_latent=self.opts.z_plus_latent)`
* changing  Line 135 to `y_hat, latent = self.net.forward(x, return_latents=True, z_plus_latent=self.opts.z_plus_latent)`

**(4)** Finally, I train pSp from scratch using the following training settings:
```
python scripts/train.py \
--dataset_type=ffhq_encode \
--exp_dir=./logs/ffhq_encoder_zplus/ \
--workers=4 \
--batch_size=8 \
--test_batch_size=8 \
--test_workers=8 \
--val_interval=2500 \
--save_interval=5000 \
--encoder_type=GradualStyleEncoder \
--start_from_latent_avg \
--lpips_lambda=0.8 \
--l2_lambda=1 \
--id_lambda=0.1 \
--z_plus_latent
```

Hope this solve your questions.

**Comment by kasim0226** [comment]
Thank you for your clear reply!

**Comment by Abhishekvats1997** [comment]
@williamyang1991 are the changes you suggested to the psp decoder (stylegan) and psp code both to be made in the original psp code repo and then train ? In order to obtain the z plus encoder

**Comment by williamyang1991** [comment]
> @williamyang1991 are the changes you suggested to the psp decoder (stylegan) and psp code both to be made in the original psp code repo and then train ? In order to obtain the z plus encoder

Yes, I modify both the encoder and decoder.

**Comment by SuekyeongNam** [comment]
Hi, I tried to train psp encoder with z+ domain using customized dataset. 
And, I found **one more thing need to change** when we use original psp code repo. 
https://github.com/williamyang1991/DualStyleGAN/blob/39a9e9e8d6ea51a817ab50fbcf82d336275abf15/model/encoder/psp.py#L95C3-L96C27
