### ISSUE TITLE
Questions about stage 1 & 2 of Progressive Fine-Tuning

### ISSUE THREAD

**Issue by kasim0226** [williamyang1991/DualStyleGAN#16]
I have some questions about stage 1 & 2 of Pretrain DualStyleGAN on FFHQ. 
Could you help me?

1. Could I use the pretrained model you provided (showing below) on several different dataset that I collected them myself.
![image](https://user-images.githubusercontent.com/5126656/163768709-2ad145c4-3213-455f-98f5-136577d3cc93.png)

2. I only find out stage 2 codes in pretrain_dualstylegan.py. Could you showd me codes of Stage 1 in pretrain_dualstylegan.py?

3. I am not understand stage1 very well from paper. In stage 1, you trained color transform blocks with style mixing FFHQ images?
The purple hair in following figure you showed it on purpose. In most cases, it is regular hair color (black, yellow, ...) when we train model in stage1, right?
![image](https://user-images.githubusercontent.com/5126656/163770696-6142aa25-1b3b-49f7-b4b6-71dabd9207b8.png)

4. In stage 2, you mentioned you sampled z2~ from **{z2,E(g(z2))}**. Could I know why you do it this way instead of only z2 or E(g(z2)).
![image](https://user-images.githubusercontent.com/5126656/163769998-1e2c91d7-d771-4b04-9db0-c1a9b6cb9d52.png)

Looking forward to your reply

**Comment by williamyang1991** [comment]
> 1. Could I use the pretrained model you provided (showing below) on several different dataset that I collected them myself.

Yes. You don't need to pretrained another model. 
This model is pretrained on FFHQ, independent of the extrinsic styles, thus it can be applied to any extrinsic styles.

> 2. I only find out stage 2 codes in pretrain_dualstylegan.py. Could you showd me codes of Stage 1 in pretrain_dualstylegan.py?

Stage 1 initializes the extrinsic style path, which I directly put in the model initialization function `__init__()`:

https://github.com/williamyang1991/DualStyleGAN/blob/39a9e9e8d6ea51a817ab50fbcf82d336275abf15/model/dualstylegan.py#L33-L36

https://github.com/williamyang1991/DualStyleGAN/blob/39a9e9e8d6ea51a817ab50fbcf82d336275abf15/model/dualstylegan.py#L69-L72

> 3. I am not understand stage1 very well from paper. In stage 1, you trained color transform blocks with style mixing FFHQ images?
>    The purple hair in following figure you showed it on purpose. In most cases, it is regular hair color (black, yellow, ...) when we train model in stage1, right?

Yes. the purple hair is just for easy visualization of color transfer. In most cases, the sampled faces have regular hair color.

> 4. In stage 2, you mentioned you sampled z2~ from **{z2,E(g(z2))}**. Could I know why you do it this way instead of only z2 or E(g(z2)).

Because we want the extrinsic style path to work for both the randomly sampled latent code or latent code embeded from style image. These two kinds of latent codes have different distributions.

**Comment by kasim0226** [comment]
Thank you for quick and clear reply.
Based on your reply, Stage 1 doesn't involve any training, am I right?

**Comment by williamyang1991** [comment]
Yes. No training is required.

**Comment by kasim0226** [comment]
Thank you for answering
