### ISSUE TITLE
When will destylization finish

### ISSUE THREAD

**Issue by cihankaradogan** [williamyang1991/DualStyleGAN#23]
I am experimenting DualStyleGAN with my custom dataset. I have 283 images and I trained StyleGAN for 600 iterations. Then, I started to destylize it. I set 300 iterations and 4 batch. I expected for it to end when it became 283/283 but now it continues. 
**[448/283] Lperc: 1.254; Lnoise: 0.000; LID: 0.100; Lreg: 0.315; lr: 0.000: 100%**  Also, I'm not sure if the destylization outputs are as they should be.
![5833 (1)](https://user-images.githubusercontent.com/58830806/166962139-504f667e-0c35-4a6e-a6ec-4392fef111f1.png)
![7629](https://user-images.githubusercontent.com/58830806/166962171-fbe1f4d0-9e54-4592-aa9b-bf3f92647148.png)

**Comment by williamyang1991** [comment]
Sorry, I made a mistake in the code when printing the progress information
https://github.com/williamyang1991/DualStyleGAN/blob/7a1c560f7fefece00a53e4406d624ad4fd8fc742/destylize.py#L192

The information should be printed as
``` 
f"[{ii:03d}/{len(files):03d}]"
```
rather than the original 
```
f"[{ii * args.batch:03d}/{len(files):03d}]"
```

So your progress at [448/283] should be [112/283]

-------------

I think your Simpsons style is too abstract and different from real human faces, and it is not well aligned (the eye positions of your two style images differ a lot from each other and from the FFHQ faces).
These two points make the destylization fail. 

Our method is to simulate the fine-tuning behavior of StyleGAN, and style transfer by fine-tuning StyleGAN relies on the **close semantic correspondences between the source domain and the target domain**, which is true for real faces and cartoon faces. However, in your case, the domain gap is so large that I'm afraid even fine-tuning StyleGAN cannot work, let alone our method.
I think you can check the performance of your finetune StyleGAN on your Simpsons styles and see whether it works. If it does not work, I guess our method might not be able to make it, either.

**Comment by williamyang1991** [comment]
this code printing the progress info has been fixed
