### ISSUE TITLE
 Progressive Fine-Tuning Stage 1 & 2

### ISSUE THREAD

**Issue by Schatzmin** [williamyang1991/DualStyleGAN#32]
In Progressive Fine-Tuning Stage 1 & 2, you didn't use any style dataset or fine-tuned stylegan on style dataset, why does the result have kind of extrinsic style?

**Comment by williamyang1991** [comment]
Progressive Fine-Tuning Stage 1 & 2 transfers the color and some structure style of realistic face images. 
The extrinsic style here is the style of realistic face images. 
Please refer to our paper for the details.

**Comment by Schatzmin** [comment]
![image](https://user-images.githubusercontent.com/93251898/172122683-421e949b-d434-4581-8b54-ffcfd88960e7.png)
But why the results of Stage 1 & 2 are seemed as the color and structural transferred styles of the examples seen in the lower-left corners? I'm a little confused...

**Comment by williamyang1991** [comment]
Because both the realistic face images and the cartoon images use the same psp encoder. 
It means psp encoder will map both the realistic face images and the cartoon images into a shared style space, which captures the color and structural styles of the input image.
Even Stage 1 & 2 uses the extrinsic style code of realistic face images for training, during testing we can still use the extrinsic style code of cartoon images.

**Comment by Schatzmin** [comment]
Does this mean：
1. psp encoder wasn't trained on cartoon images?
2. Stage 1 & 2 don't show the style of cartoon style during training?

**Comment by Schatzmin** [comment]
I got it! Thanks a lot!!!
