### ISSUE TITLE
convert_weight from .pkl to .pt

### ISSUE THREAD

**Issue by Schatzmin** [williamyang1991/DualStyleGAN#33]
I noticed that your [stylegan2-ffhq-config-f.pt](https://drive.google.com/file/d/1EM87UquaoQmk17Q8d5kYIAHqu0dkYqdT/view) is taken from [rosinality](https://github.com/rosinality/stylegan2-pytorch).
Have you ever used the **convert_weight.py** in the [rosinality](https://github.com/rosinality/stylegan2-pytorch)?

I just used the **convert_ weight. py** to convert **generator_yellow-stylegan2-config-f.pkl** to .pt file, but there is a **KeyError** occurs when loading .pt. Can you tell me which key in the .pt corresponds to which key in the .pkl? Especially the 'g_ema'. Or something else was wrong?
![image](https://user-images.githubusercontent.com/93251898/172157842-f0c1ed4b-8346-461d-a0f3-48530099efa4.png)
![image](https://user-images.githubusercontent.com/93251898/172157906-2c481550-8a40-4577-aec3-eca52be3f8c8.png)
![image](https://user-images.githubusercontent.com/93251898/172158346-3eaef40c-6687-4e01-955f-7b7924e71ea6.png)

Figure 1 is the BUG.
Figure 2 is your **finetune_stylegan.py**.
Figure 3 is the official [stylegan2](https://github.com/NVlabs/stylegan2)'s  **run_training.py** based on TensorFlow.

**Comment by williamyang1991** [comment]
I directly used [stylegan2-ffhq-config-f.pt](https://drive.google.com/file/d/1EM87UquaoQmk17Q8d5kYIAHqu0dkYqdT/view) without using convert_weight.py.
So I have no idea of your bug.
Maybe you can open an issue in the [rosinality](https://github.com/rosinality/stylegan2-pytorch)'s page.

**Comment by Schatzmin** [comment]
I have solved it. Thank you for your timely reply!

**Comment by howon52** [comment]
Hello, might I enquire how this issue was resolved? @Schatzmin 
I'm experiencing similar difficulties:
The [rosinality](https://github.com/rosinality/stylegan2-pytorch) seems only to show [550000.pt](https://drive.google.com/file/d/1PQutd-JboOCOZqmd95XWxWrO8gGEvRcO/view) as the pretrained model, which is different from the [stylegan2-ffhq-config-f.pt](https://drive.google.com/file/d/1EM87UquaoQmk17Q8d5kYIAHqu0dkYqdT/view) from the README.

Sorry to bring back up such an old issue from more than a year back, but would appreciate any help. Thank you~!
