### ISSUE TITLE
Can you provide the slamdunk dataset？

### ISSUE THREAD

**Issue by SUNFOLWER** [williamyang1991/DualStyleGAN#35]
I want slamdunk, Pixar, comic and arcane datasets, thank you very much!

**Comment by williamyang1991** [comment]
Thank you for your interest.
The  slamdunk, Pixar, comic and arcane datasets we used are collected from the Internet.
Since we do not have the copyrights, we feel sorry that we cannot make these datasets public according to the suggestion of our industry partner.

The good news is that I recorded some meta information when I collected the arcane and pixar datasets. 
You can create your own arcane and pixar datasets following [build-your-own-dataset](https://github.com/williamyang1991/DualStyleGAN/tree/main/data_preparation#build-your-own-dataset)

**Comment by SUNFOLWER** [comment]
I see. Thank you for your reply.
