### ISSUE TITLE
Where can I find the pixar dataset?

### ISSUE THREAD

**Issue by echo1993in** [williamyang1991/DualStyleGAN#65]

**Comment by williamyang1991** [comment]
https://github.com/williamyang1991/DualStyleGAN/issues/8#issuecomment-1082753093

Thank you for your interest.
The pixar dataset we used are collected from the Internet.
Since we do not have the copyrights, we feel sorry that we cannot make this dataset public.


However, if you want an approximate dataset without copyright issue as in [this](https://github.com/williamyang1991/DualStyleGAN/blob/main/doc_images/Reconstruction_pixar_overview.jpg), not the original dataset, 
you can use the instyle_code.npy and exstyle_code.npy to reconstruct each pixar image.

```
latent = exstyles
latent = generator.generator.style(latent.reshape(latent.shape[0]*latent.shape[1], latent.shape[2])).reshape(latent.shape)
img_gen, _ = generator([instyles], latent, use_res=True, z_plus_latent=True)
```
